config/routes.rb
Rails.application.routes.draw do
  # ---------------------------- ENTRIES CONTROLLER ----------------------------
  get 'blog' => 'binomio_blog/entries#public_index', as: 'binomio_blog'
  get 'blog/entradas' => 'binomio_blog/entries#admin_index', as: 'binomio_blog_entries'
  get 'blog/entradas/buscar' => 'binomio_blog/entries#search_entries', as: 'binomio_blog_search'
  get 'blog/entradas/nueva' => 'binomio_blog/entries#new', as: 'binomio_blog_new_entry'
  get 'blog/entradas/:id' => 'binomio_blog/entries#show', as: 'binomio_blog_entry'
  delete 'blog/entradas/:id' => 'binomio_blog/entries#destroy'
  get 'blog/entradas/:id/:url_title' => 'binomio_blog/entries#show', as: 'binomio_blog_entry_fancy'
  post 'blog/entradas/:id/set_like' => 'binomio_blog/entries#set_like', as: 'binomio_blog_set_like'
  get 'blog/ayuda' => 'binomio_blog/entries#help', as: 'binomio_blog_help'

  # ---------------------------- CATEGORIES CONTROLLER ----------------------------
  get 'blog/categorias' => 'binomio_blog/categories#index', as: 'binomio_blog_categories'
  get 'blog/categorias/nueva' => 'binomio_blog/categories#new', as: 'binomio_blog_new_category'
  delete 'blog/categorias/:id' => 'binomio_blog/categories#destroy', as: 'binomio_blog_category'
end

app/models/binomio_blog/category.rb
module BinomioBlog
  class Category < ActiveRecord::Base
    self.table_name = 'binomio_blog_categories'

    has_many :entries
    validates :name, presence: true, length: { maximum: 64 }, uniqueness: true
    validates :url_name, presence: true, length: { maximum: 64 }, uniqueness: true, format: { with: /\A[a-z0-9-]+\z/ }
  end
end

app/models/binomio_blog/entry.rb
module BinomioBlog
  class Entry < ActiveRecord::Base
    self.table_name = 'binomio_blog_entries'
    enum status: { published: 1, unlisted: 2, disabled: 3, draft: 4 }
    PRETTY_STATUSES = { published: 'Publicada', unlisted: 'Sin listar', disabled: 'Deshabilitada', draft: 'Borrador' }

    belongs_to :category, optional: true
    has_many :likes

    has_one_attached :head_image

    validates :status, presence: true
    validates :title, presence: true, length: { maximum: 128 }
    validates :content, presence: true, length: { maximum: 32768 }
    validates :author_name, presence: true, length: { maximum: 64 }
    validates :author_role, presence: true, length: { maximum: 64 }
    validates :view_count, presence: true
    validates :published_at, presence: true

    # Generate a string that matches the Entry's title but in a URL-safe way. This allows
    # us to append it to the Entry's URL for SEO improvement purposes.
    def url_title
      self.title.parameterize
    end

    # Given an IP address, add a like to this Entry unless the IP address has already
    # done so before. Returns true if the like was added, false otherwise.
    def add_like_by(ip_address)
      if likes.exists?(ip: ip_address)
        return false
      else
        Like.create!({entry_id: self.id, ip: ip_address})
        return true
      end
    end

    # If the given address has liked this Entry, remove the like
    def remove_like_by(ip_address)
      likes.where(ip: ip_address).delete_all
    end

    def like_count
      self.likes.count
    end

    def pretty_status
      PRETTY_STATUSES[self.status.to_sym] || "?"
    end

    def thumbnail
      if self.head_image.attached?
        self.head_image.variant(combine_options: {thumbnail: '600x400^', gravity: 'center', extent: '600x400'})
      else
        nil
      end
    end

    # Create a random blog entry. Creates a random amount of likes associated too.
    def self.create_random!
      entry = Entry.create!(
        category: Category.count > 0 ? Category.limit(1).order("RANDOM()").first : nil,
        status: 'published',
        title: Lipsum.words(2..12).capitalize,
        content: Lipsum.paragraphs(1..10),
        author_name: "John Doe",
        author_role: "Tester",
        view_count: rand(0..9999),
        published_at: rand(0..700).days.ago
      )
      rand(1..20).times do |i|
        entry.add_like_by "#{i}.#{rand(0..255)}.#{rand(0..255)}.#{rand(0..255)}"
      end
    end

  end
end

app/models/binomio_blog/like.rb
module BinomioBlog
  class Like < ActiveRecord::Base
    self.table_name = 'binomio_blog_likes'

    belongs_to :entry
    validates :ip, presence: true, format: { with: /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/ }
  end
end

app/controllers/binomio_blog/binomio_blog_controller.rb
module BinomioBlog
  # All the controllers within this gem inherit from this parent controller
  class BinomioBlogController < ApplicationController

    protected

    def authorize_for_blog_edition
      authenticate_user!
      redirect_to binomio_blog_path unless BinomioBlog.authorized_for_edition?(current_user)
    end

  end
end

app/controllers/binomio_blog/categories_controller.rb
module BinomioBlog
  class CategoriesController < BinomioBlogController
    before_action do authorize_for_blog_edition end

    def index
      @categories = Category.all
    end

    def new
      category_name = "Nueva categoría"
      category_url_name = category_name.parameterize
      counter = 2
      while Category.exists?(name: category_name) || Category.exists?(url_name: category_url_name)
        category_name = "Nueva categoría #{counter}"
        category_url_name = category_name.parameterize
        counter += 1
      end
      Category.create!(name: category_name, url_name: category_url_name)
      redirect_to binomio_blog_categories_path
    end

    def destroy
      Category.find(params[:id]).destroy
      redirect_to binomio_blog_categories_path
    end
  end
end

app/controllers/binomio_blog/entries_controller.rb
module BinomioBlog
  class EntriesController < BinomioBlogController
    ENTRIES_PER_PAGE = 12 # When using infinite scroll, entries will be loaded in batches of this many
    before_action except: [:public_index, :show, :search_entries] do authorize_for_blog_edition end
    before_action only: [:show, :set_like] do set_entry end

    # The table of entries for administrators
    def admin_index
      @entries = Entry.all.order(published_at: :desc)
    end

    # The page that visitors see as the "home page" of the blog
    def public_index
    end

    # This method is called by public_index via AJAX. It returns a partial HTML containing the list of results, filtered by category,
    # and with a given offset, which is then injected into the DOM
    def search_entries
      offset = params[:offset].to_i
      entries = Entry.published.order(published_at: :desc).offset(offset).limit(ENTRIES_PER_PAGE)
      # Filter by category if applicable
      category = params[:category].present? ? Category.find_by_name(params[:category]) : nil
      entries = entries.where(category_id: category.id) if category.present?
      render partial: 'entry_list', locals: { entries: entries }
    end

    def new
      @entry = Entry.create!(
        status: 'draft',
        title: "Nueva entrada",
        content: "Contenido de la entrada aquí",
        author_name: "Autor",
        author_role: "Rol",
        view_count: 0,
        published_at: DateTime.now
      )
      redirect_to binomio_blog_entry_fancy_path(id: @entry.id, url_title: @entry.url_title)
    end

    def show
      if @entry.url_title != params[:url_title]
        redirect_to binomio_blog_entry_fancy_path(id: @entry.id, url_title: @entry.url_title)
      end
      if @entry.disabled? && !authorized_for_edition?
        redirect_to binomio_blog_path
      end
      unless user_signed_in?
        @entry.view_count += 1
        unless @entry.save
          puts "Failed to increase view count of BinomioBlog Entry: #{@entry.errors.full_messages[0]}"
        end
      end
    end

    # Permanently delete an Entry
    def destroy
      Entry.find(params[:id]).destroy
      redirect_to binomio_blog_entries_path
    end

    # Adds or removes a like from the requesting IP to the referenced Entry
    def set_like
      if params[:like] == 'true'
        @entry.add_like_by(request.ip)
      else
        @entry.remove_like_by(request.ip)
      end
      head 200
    end

    # Remove a like from the referenced Entry
    def unlike
      @entry.remove_like_by(request.ip)
      head 200
    end

    private

    def set_entry
      @entry = Entry.find params[:id]
    end
  end
end

app/helpers/binomio_blog/entries_helper.rb
module BinomioBlog
  module EntriesHelper

    def authorized_for_blog_edition?(user = current_user)
      BinomioBlog.authorized_for_edition? user
    end

  end
end

app/views/binomio_blog/categories/index.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-md-11 col-lg-10 col-xl-9 pt-3">
    <h1>Categorías</h1>
    <table class="table mt-3">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Nombre en URL</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= editable_text category, :name %></td>
            <td><%= editable_text category, :url_name %></td>
            <td><a href="<%= binomio_blog_category_path(category) %>" data-method="delete" data-confirm="¿Borrar la categoría <%= category.name%>?" class="btn btn-danger">Borrar</a></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <a href="<%= binomio_blog_new_category_path %>" class="btn btn-primary">Nueva categoría</a>
  </div>
</div>

app/views/binomio_blog/entries/_entry_list.html.erb
<% entries.each do |entry| %>
  <div class="col-12 col-sm-6 col-lg-4 entry-col">
    <%= link_to binomio_blog_entry_fancy_path(id: entry.id, url_title: entry.url_title), class: "w-100" do %>
      <div class="entry my-3">
        <% if entry.head_image.attached? %>
          <%= image_tag entry.thumbnail %>
        <% else %>
          <%= image_tag "binomio_blog/default_thumbnail.jpg" %>
        <% end %>
        <div class="p-3">
          <h2><%= entry.title %></h2>
          <p class="entry-description"><%= entry.content.gsub(/<[^>]+>/, '').first(100) %></p>
          <span class="entry-date">Hace <%= time_ago_in_words(entry.published_at) %></span>
          <% if entry.category.present? %>
            <span class="entry-category"><%= entry.category.name %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/binomio_blog/entries/admin_index.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-md-11 col-lg-10 col-xl-9 pt-3">
    <h1>Entradas</h1>
    <table class="table mt-3">
      <thead>
        <tr>
          <th>Estado</th>
          <th>Publicación</th>
          <th>Título</th>
          <th>Autor</th>
          <th>Categoría</th>
          <th>Vistas</th>
          <th>Likes</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @entries.each do |entry| %>
          <tr>
            <td><%= editable_select entry, :status, BinomioBlog::Entry::PRETTY_STATUSES.map{|original, pretty| [pretty, original]}, class: "form-control" %></td>
            <td>Hace <%= time_ago_in_words entry.published_at %></td>
            <td><%= link_to entry.title, binomio_blog_entry_fancy_path(id: entry.id, url_title: entry.url_title) %></td>
            <td><%= entry.author_name %></td>
            <td><%= entry.category&.name || "-" %></td>
            <td><%= entry.view_count %></td>
            <td><%= entry.like_count %></td>
            <td><a href="<%= binomio_blog_entry_path(entry) %>" data-method="delete" data-confirm="¿Borrar la entrada <%= entry.title %>?" class="btn btn-danger">Borrar</a></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <a href="<%= binomio_blog_new_entry_path %>" class="btn btn-primary">Nueva entrada</a>
  </div>
</div>

app/views/binomio_blog/entries/help.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-md-11 col-lg-10 col-xl-9 pt-3">
    <h1>Binomio Blog</h1>

    <h2>Estados</h2>
    Cada entrada del blog puede estar en uno de 4 diferentes estados:
    <ul>
      <li><b>Borrador</b>: Un post que aún no está listo para publicarse.</li>
      <li><b>Publicado</b>: Un post visible por los visitantes.</li>
      <li><b>Deshabilitado</b>: Un post dado de baja, no visible para los visitantes.</li>
      <li><b>Sin listar</b>: Un post que no se muestra en la lista de entradas, pero accesible a través del link directo.</li>
    </ul>

    <h2>Likes</h2>
    Cualquier visitante del blog puede dar like a un post haciendo clic en el ícono correspondiente. Cada dirección IP puede dar like a una entrada una sola vez.

    <h2>Vistas</h2>
    El contador de vistas cuenta cuántas veces se ha mostrado la página de cada entrada. Solamente se cuentan las vistas por usuarios no registrados.
  </div>
</div>

app/views/binomio_blog/entries/public_index.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-md-11 col-lg-10 col-xl-9 pt-3">
    <h1 class="d-inline-block">Blog</h1>
    <button id="btnResetFilters" class="btn btn-secondary float-right d-none" onclick="setCategory(null)">Quitar filtro</button>
    <div id="divEntries" class="row">

    </div>
  </div>
</div>
<style>
  .entry-col > a {
    color: #333;
    text-decoration: none;
  }
  .entry {
    box-shadow: 1px 1px 3px grey;
    border-radius: 5px;
    transition: box-shadow 0.5s;
  }
  .entry:hover {
    box-shadow: 1px 1px 5px #333;
  }
  .entry h2 {
    font-size: 20px;
    font-weight: bold;
  }
  .entry > img {
    width: 100%;
    border-top-right-radius: 5px;
    border-top-left-radius: 5px;
  }
  .entry > div {
    padding: 10px;
  }
  .entry-description {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  .entry-date {
    color: grey;
    font-size: 80%;
  }
  .entry-category {
    float: right;
    padding: 2px 5px;
    background-color: #9b9bff;
    color: white;
    font-size: 12px;
    border-radius: 5px;
  }
</style>
<script>
  var currentOffset = 0; // The offset from which to display Entries (starting from the most recent Entry)
  var reachedLimit = false; // If this is true, it means there are no Entries left to fetch from the server
  var categoryToFilter = null; // The name of the Category to filter Entries for, or null if no filtering is desired
  $(function() {
    loadMoreEntries();
    // When the user scrolls to the bottom of the page, load more entries
    $(window).scroll(function() {
      if(!reachedLimit && $(window).scrollTop() + $(window).height() == $(document).height()) {
        loadMoreEntries();
      }
    });
  });
  // Fetch Entries from the server in HTML format and inject them into the DOM
  function loadMoreEntries() {
    console.log("Loading entries with offset " + currentOffset);
    $.ajax({
      url: "<%= binomio_blog_search_path %>",
      data: {
        offset: currentOffset,
        category: categoryToFilter
      },
      success: function(res) {
        $("#divEntries").append(res);
        currentOffset += <%= BinomioBlog::EntriesController::ENTRIES_PER_PAGE %>;
        if (res.length == 0) { // If the server replied with blank HTML it means there are no more Entries left
          reachedLimit = true;
        }
        // When the user clicks on a category tag, filter the Entries by that category
        $(".entry-category").click(function(evt) {
          evt.preventDefault();
          setCategory(evt.currentTarget.innerText);
        });
      }
    });
  }
  // Choose a new category to show Entries for
  function setCategory(category) {
    if (category != categoryToFilter) {
      categoryToFilter = category;
      resetEntries();
      loadMoreEntries();
    }
    $("#btnResetFilters").toggleClass("d-none", category == null); // Hide the "reset filters" button when no category filter is present
  }
  // Clear all the Entries being displayed and start again from offset 0
  function resetEntries() {
    $("#divEntries").html("");
    currentOffset = 0;
  }
</script>

app/views/binomio_blog/entries/show.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-md-10 col-lg-8 col-xl-6 pt-3">
    <h1><%= editable_text @entry, :title %></h1>
    <hr/>
    <% if @entry.head_image.attached? || authorized_for_blog_edition? %>
      <%= editable_image @entry, :head_image, { missing_image: "binomio_blog/default_thumbnail.jpg" }, class: "entry-image" %>
    <% end %>
    <hr/>
    <div>
      <%= editable_text @entry, :content, rich: true %>
    </div>
    <hr/>
      <i>Publicado por <%= editable_text @entry, :author_name %> (<%= editable_text @entry, :author_role %>)</i>
      <span style="float:right; color: #444">
        <i class="fa fa-eye mr-2"></i><%= @entry.view_count %>
        <i class="fa fa-heart like-icon mx-1 ml-3"></i><%= @entry.like_count %>
      </span>
    <hr/>
    <% if authorized_for_blog_edition? %>
      <label>Estado: <%= editable_select @entry, :status, BinomioBlog::Entry::PRETTY_STATUSES.map{|original, pretty| [pretty, original]}, class: "form-control" %></label><br/>
      <label>Categoría: <%= editable_select @entry, :category_id, BinomioBlog::Category::all.map{|cat| [cat.name, cat.id]}, class: "form-control" %></label><br/>
    <% end %>
  </div>
</div>
<style>
  .entry-image {
    max-width: 100%;
  }
  .like-icon {
    cursor: pointer;
    padding: 4px;
  }
  .like-icon.liked {
    color: #f72a4e;
  }
</style>
<script>
  // When the like button is clicked, send an AJAX request and color the icon pink if successful
  $(".like-icon").click(function(evt) {
    $.ajax({
      url: "<%= binomio_blog_set_like_path %>",
      type: "post",
      data: {
        like: !$(evt.currentTarget).hasClass("liked")
      },
      success: function() {
        $(evt.currentTarget).toggleClass("liked");
      }
    });
  });
</script>